### ISSUE TITLE
profile card - Like/noLikeStatus/Dislike button

### ISSUE THREAD

**Issue by jalalhobbs** [jalalhobbs/MatchMaking1#29]
Buttons only function on last listed profile card on home page. Clicking on a button on the profile card causes browser to go to page posted to.

All forms have the same name, js targets form to allow post by clicking radio button, but since they are dynamically generated, they have the same name and cannot be reliably referenced on the server if we dynamically name the forms.

**Comment by bourkg** [comment]
like dislike button implemented
