### ISSUE TITLE
My Profile DOB restriction not correct

### ISSUE THREAD

**Issue by jalalhobbs** [jalalhobbs/MatchMaking1#56]
![image](https://user-images.githubusercontent.com/4069347/39903117-b89baa70-5510-11e8-84e5-c5f8a276e425.png)

DOB 02/01/1900, which is in range of error message returns error message:

> The dob must be a date after 1900-01-01.

**Comment by jalalhobbs** [comment]
01/01/1901 doesn't work
01/01/1902 works

**Comment by dlrmit** [comment]
strange bug... now corrected to make DOB > 1905. Something wong/weird about 1900.

**Comment by jalalhobbs** [comment]
works with 01/02/1905, doesn't work with 31/12/1904 or 01/01/1905, as detailed. closing
