### ISSUE TITLE
flash message typo in ProfileController

### ISSUE THREAD

**Issue by jalalhobbs** [jalalhobbs/MatchMaking1#57]
`$request->session()->flash('status', 'Your Profile has been updated. Please tell us more about who you are looking for. Leave out anything which you dont mind.');`

dont -> don't

Maybe quick rewording.

**Comment by dlrmit** [comment]
Apostrophes are like death here. Because it is hard to get a string literal/escape in this situation. Avoid apostrophes

**Comment by dlrmit** [comment]
FIXED! replaced with             $request->session()->flash('status', 'Your Profile has been updated. Please tell us more about who you are looking for. Leave out anything which is optional.');

**Comment by jalalhobbs** [comment]
the typo is fixed, looks good to me.
