### ISSUE TITLE
Register page accepting Welcome controller registration does not yield Gender names

### ISSUE THREAD

**Issue by jalalhobbs** [jalalhobbs/MatchMaking1#58]
It also does not allow other options.
![image](https://user-images.githubusercontent.com/4069347/39903456-737594e0-5512-11e8-8947-834e9b61e2c5.png)
![image](https://user-images.githubusercontent.com/4069347/39903475-8eb5700e-5512-11e8-8a95-ef16b287b3ec.png)

**Comment by jalalhobbs** [comment]
`Confirm Password` is separated from `Password`

**Comment by dlrmit** [comment]
This was going to be the backup way to fix current issue. Accidentally left in place (will become a hidden field but is showing for purpose of testing and eval).

**Comment by dlrmit** [comment]
FIXED! now hidden!

**Comment by jalalhobbs** [comment]
fixed, I don't see them. closing
