### ISSUE TITLE
TargetGenderId is not retained through Welcome->Registration

### ISSUE THREAD

**Issue by jalalhobbs** [jalalhobbs/MatchMaking1#59]
When using the Welcome page to select a `targetGenderId`, `targetGenderId` is not saved to the DB

**Comment by jalalhobbs** [comment]
It will show a `targetGenderId` selected under `Looking For ...`, but it is not saved in the DB or used for selecting potential matches.
After removing cookies and logging in again, the `targetGenderId` will be removed from the `Looking For ...` page.

**Comment by dlrmit** [comment]
Tried to save in DB previously. Will try again later to see if this can be addressed during registration.

**Comment by dlrmit** [comment]
fixed.... I forgot to make it mass-assignable. do'h.

**Comment by jalalhobbs** [comment]
works for me. closing it
