### ISSUE TITLE
IE11: footer floats in the middle of display on Welcome page

### ISSUE THREAD

**Issue by jalalhobbs** [jalalhobbs/MatchMaking1#73]
![image](https://user-images.githubusercontent.com/4069347/40088910-62a5da56-58e8-11e8-81c1-11b42e699e53.png)

User base of IE11 is very small @ 2.23% in Australia per CanIUse.com

**Comment by dlrmit** [comment]
Suggestion: just put the footer info links into the header bar, we'll have no footer then.

**Comment by jalalhobbs** [comment]
![image](https://user-images.githubusercontent.com/4069347/40220205-7a97bf00-5ab7-11e8-9ac5-92d5836193bc.png)
The labels stack incorrectly when on small displays, I'm just cleaning up the html/classes
